### PR TITLE
solve issue 1 test 2 has been skipped

### LINKED ISSUE #1: See all reminders
- When the user visits the root of the application (e.g. the "/" URL), they should see a list of all of the reminders on the page.
- Each reminder should have a class of `.spec-reminder-item`.

There is a failing test set up in `tests/acceptance/reminder-list-test.js`.

**Hot Tip**: If you name your pull request or even your commit with "Closes #1", it will automatically close this issue when it successfully merged into master.

### PR DESCRIPTION
**Pull request by Peter-Springer**
@stevekinney @brittanystoroz @martensonbj @tehviking
## Purpose

Needed to set up model, template, route and router in order to render reminders to the route '/'.
https://github.com/turingschool-projects/1606-remember-3/issues/1

## Approach

This change addressed the problem by allowing the user to see the list.

### Learning

We got burned by naming things application and then referenced the ember docs and grocery-list.
Finally we reached out to Brandon for help.
http://emberjs.com/

### Open Questions and Pre-Merge TODOs

- [] Use Github checklists. When solved, check the box and explain the answer.

### Test coverage 

_Briefly describe what tests you have written and why._

### Merge Dependencies and Related Work

_Link to merge dependency issues or PRs._

### Follow-up tasks

- [Issue #2 (Example)](https://github.com/flexyford/pull-request/issues)

#### Before
screen shot 2016-10-12 at 4 21 15 pm
#### After
screen shot 2016-10-12 at 4 20 49 pm

closes #1

### CODE REVIEW

File: app/models/reminder.js [hunk 1]
```diff
@@ -0,0 +1,8 @@
+import DS from 'ember-data';
+
+export default DS.Model.extend({
+  title: DS.attr('string'),
+  date: DS.attr('date'),
+  notes: DS.attr('string'),
+  pinned: DS.attr('boolean')
```
Comment (stevekinney) [inline app/models/reminder.js]: Can you set the default value of this property to `false`?

File: app/routes/reminders.js [hunk 2]
```diff
@@ -0,0 +1,7 @@
+import Ember from 'ember';
+
+export default Ember.Route.extend({
+  model: function() {
```
Comment (stevekinney) [inline app/routes/reminders.js]: Let's use the the ES6 syntax.

```
model() {
  // stuff…
}
```

File: app/templates/reminders.hbs [hunk 3]
```diff
@@ -0,0 +1,11 @@
+<div class="template">
+  <h2>REMINDERS</h2>
```
Comment (stevekinney) [inline app/templates/reminders.hbs]: This seems like boiler plate that should go in the application template.

File: app/templates/reminders.hbs [hunk 4]
```diff
@@ -0,0 +1,11 @@
...
+
+  <ul>
```
Comment (stevekinney) [inline app/templates/reminders.hbs]: This should stay in this template, but I don't think an `<li>` is the right element.

What about `<section>` and `<article>` elements?

File: app/models/reminder.js (hunk 1 above)
Comment (Peter-Springer) [inline app/models/reminder.js]: which property pinned?

File: app/routes/reminders.js (hunk 2 above)
Comment (Peter-Springer) [inline app/routes/reminders.js]: update has been made on issue-1 branch

File: app/templates/reminders.hbs (hunk 3 above)
Comment (Peter-Springer) [inline app/templates/reminders.hbs]: removed boiler plate

File: app/models/reminder.js [hunk 5]
```diff
@@ -4,5 +4,5 @@ export default DS.Model.extend({
   title: DS.attr('string'),
   date: DS.attr('date'),
   notes: DS.attr('string'),
-  pinned: DS.attr('boolean')
+  pinned: false
```
Comment (stevekinney) [inline app/models/reminder.js]: Check out the documentation for how to implement this here: https://guides.emberjs.com/v2.4.0/models/defining-models/#toc_options

File: app/templates/reminders.hbs (hunk 4 above)
Comment (Peter-Springer) [inline app/templates/reminders.hbs]: updated ul and li to section and article

File: app/models/reminder.js (hunk 5 above)
Comment (Peter-Springer) [inline app/models/reminder.js]: That was helpful thanks!
